site_name: The Blue Book
site_description: My second brain
site_author: Lyz
site_url: https://lyz-code.github.io/blue-book
nav:
  - Introduction: 'index.md'
  - Meta: 'meta/meta.md'
  - Projects: 'projects/projects.md'
  - Wish list: 'wish_list.md'
  - Life Automation:
    - Life Automation: 'life_automation/life_automation.md'
    - Week Automation: 'life_automation/week_automation.md'
  - DevOps:
    - DevOps: 'devops/devops.md'
    - Kubernetes:
      - Kubernetes: 'devops/kubernetes/kubernetes.md'
      - Architecture: 'devops/kubernetes/kubernetes_architecture.md'
      - Resources:
        - Namespaces: 'devops/kubernetes/kubernetes_namespaces.md'
        - Pods: 'devops/kubernetes/kubernetes_pods.md'
        - ReplicaSets: 'devops/kubernetes/kubernetes_replicasets.md'
        - Deployments: 'devops/kubernetes/kubernetes_deployments.md'
        - Horizontal Pod Autoscaling: 'devops/kubernetes/kubernetes_hpa.md'
        - Volumes: 'devops/kubernetes/kubernetes_volumes.md'
        - Services: 'devops/kubernetes/kubernetes_services.md'
        - Labels: 'devops/kubernetes/kubernetes_labels.md'
        - Annotations: 'devops/kubernetes/kubernetes_annotations.md'
        - Ingress: 'devops/kubernetes/kubernetes_ingress.md'
        - Operators: 'devops/kubernetes/kubernetes_operators.md'
      - Kubectl:
        - Kubectl: 'devops/kubectl/kubectl.md'
        - Kubectl Installation: 'devops/kubectl/kubectl_installation.md'
      - Additional Components:
        - Metrics Server: 'devops/kubernetes/kubernetes_metric_server.md'
        - Ingress Controller: 'devops/kubernetes/kubernetes_ingress_controller.md'
        - External DNS: 'devops/kubernetes/kubernetes_external_dns.md'
        - Cluster Autoscaler: 'devops/kubernetes/kubernetes_cluster_autoscaler.md'
        - Dashboard: 'devops/kubernetes/kubernetes_dashboard.md'
        - Storage Driver: 'devops/kubernetes/kubernetes_storage_driver.md'
        - Vertical Pod Autoscaler: 'devops/kubernetes/kubernetes_vertical_pod_autoscaler.md'
      - Networking: 'devops/kubernetes/kubernetes_networking.md'
      - Tools: 'devops/kubernetes/kubernetes_tools.md'
    - Helm:
      - Helm: 'devops/helm/helm.md'
      - Helm Installation: 'devops/helm/helm_installation.md'
      - Helm Commands: 'devops/helm/helm_commands.md'
      - Helm Secrets: 'devops/helm/helm_secrets.md'
    - Helmfile: 'devops/helmfile.md'
    - Prometheus:
      - Prometheus: 'devops/prometheus/prometheus.md'
      - Architecture: 'devops/prometheus/prometheus_architecture.md'
      - Prometheus Operator: 'devops/prometheus/prometheus_operator.md'
    - AWS:
      - AWS: 'devops/aws/aws.md'
      - IAM:
        - IAM: 'devops/aws/iam/iam.md'
        - IAM Commands: 'devops/aws/iam/iam_commands.md'
        - IAM Debugging: 'devops/aws/iam/iam_debug.md'
  - Linux:
    - LUKS: 'linux/luks/luks.md'
    - rm: 'linux/rm.md'
    - zip: 'linux/zip.md'
  - Contact: 'contact.md'
  - Emojis: 'emojis.md'
  - Tags: 'tags.md'

plugins:
  - search
  - tags:
  - autolinks
  - git-revision-date-localized:
      type: timeago
  - minify:
      minify_html: true
  # - htmlproofer
  # - tooltipster-links
  # - vim-md-tags

markdown_extensions:
  - admonition
  - meta
  - toc:
      permalink: true
      baselevel: 2
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
theme:
  name: material
  custom_dir: "theme"
  logo: "images/logo.bmp"
  palette:
    primary: 'blue grey'
    accent: 'light blue'
  static_templates:
    - rss.xml

extra_css:
  - 'stylesheets/extra.css'
  - 'stylesheets/links.css'
  # - 'stylesheets/tooltipster.bundle.min.css'

# extra_js:
#   - 'javascript/tooltipster.bundle.js'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/lyz-code'

repo_name: 'lyz-code/blue-book'
repo_url: 'https://github.com/lyz-code/blue-book'
