---
site_name: The Blue Book
site_description: My second brain
site_author: Lyz
site_url: https://lyz-code.github.io/blue-book
nav:
  - Introduction: index.md
  - Meta:
      - Meta: meta/meta.md
      - Projects: projects/projects.md
      - Wish list: wish_list.md
  - DevOps:
      - DevOps: devops/devops.md
      - Infrastructure as Code:
          - Helm:
              - Helm: devops/helm/helm.md
              - Helm Installation: devops/helm/helm_installation.md
              - Helm Commands: devops/helm/helm_commands.md
              - Helm Secrets: devops/helm/helm_secrets.md
              - Helm Git: helm_git.md
          - Helmfile: devops/helmfile.md
      - Infrastructure Solutions:
          - Kubernetes:
              - Kubernetes: devops/kubernetes/kubernetes.md
              - Architecture: devops/kubernetes/kubernetes_architecture.md
              - Resources:
                  - Namespaces: devops/kubernetes/kubernetes_namespaces.md
                  - Pods: devops/kubernetes/kubernetes_pods.md
                  - ReplicaSets: devops/kubernetes/kubernetes_replicasets.md
                  - Deployments: devops/kubernetes/kubernetes_deployments.md
                  - Horizontal Pod Autoscaling: >-
                      devops/kubernetes/kubernetes_hpa.md
                  - Volumes: devops/kubernetes/kubernetes_volumes.md
                  - Services: devops/kubernetes/kubernetes_services.md
                  - Labels: devops/kubernetes/kubernetes_labels.md
                  - Annotations: devops/kubernetes/kubernetes_annotations.md
                  - Ingress: devops/kubernetes/kubernetes_ingress.md
                  - Operators: devops/kubernetes/kubernetes_operators.md
                  - Jobs: devops/kubernetes/kubernetes_jobs.md
              - Kubectl:
                  - Kubectl: devops/kubectl/kubectl.md
                  - Kubectl Installation: devops/kubectl/kubectl_installation.md
                  - Kubectl Commands: devops/kubectl/kubectl_commands.md
              - Additional Components:
                  - Metrics Server: devops/kubernetes/kubernetes_metric_server.md
                  - Ingress Controller: >-
                      devops/kubernetes/kubernetes_ingress_controller.md
                  - External DNS: devops/kubernetes/kubernetes_external_dns.md
                  - Cluster Autoscaler: >-
                      devops/kubernetes/kubernetes_cluster_autoscaler.md
                  - Dashboard: devops/kubernetes/kubernetes_dashboard.md
                  - Storage Driver: devops/kubernetes/kubernetes_storage_driver.md
                  - Vertical Pod Autoscaler: >-
                      devops/kubernetes/kubernetes_vertical_pod_autoscaler.md
              - Networking: devops/kubernetes/kubernetes_networking.md
              - Tools: devops/kubernetes/kubernetes_tools.md
          - AWS:
              - AWS: devops/aws/aws.md
              - Security groups workflow: devops/aws/security_groups.md
              - EKS: devops/aws/eks.md
              - IAM:
                  - IAM: devops/aws/iam/iam.md
                  - IAM Commands: devops/aws/iam/iam_commands.md
                  - IAM Debugging: devops/aws/iam/iam_debug.md
              - S3: devops/aws/s3.md
      - Continuous Integration:
          - Continuous Integration pipelines: devops/ci.md
          - Linters:
              - Alex: devops/alex.md
              - Flakehell: devops/flakehell.md
              - Flake8: devops/flake8.md
              - Markdownlint: devops/markdownlint.md
              - Proselint: devops/proselint.md
              - Yamllint: devops/yamllint.md
              - Write Good: devops/write_good.md
          - Formatters:
              - Black: devops/black.md
          - Type Checkers:
              - Mypy: devops/mypy.md
          - Security Checkers:
              - Safety: devops/safety.md
              - Bandit: devops/bandit.md
          - Dependency managers:
              - Pip-tools: devops/pip_tools.md
      - Automating Processes:
          - cookiecutter: linux/cookiecutter.md
          - cruft: linux/cruft.md
      - Monitoring:
          - Prometheus:
            - Prometheus: devops/prometheus/prometheus.md
            - Architecture: devops/prometheus/prometheus_architecture.md
            - Prometheus Operator: devops/prometheus/prometheus_operator.md
            - Prometheus Install: devops/prometheus/prometheus_installation.md
            - AlertManager: devops/prometheus/alertmanager.md
            - Blackbox Exporter: devops/prometheus/blackbox_exporter.md
            - Node Exporter: devops/prometheus/node_exporter.md
            - Instance sizing analysis: devops/prometheus/instance_sizing_analysis.md
            - Prometheus Troubleshooting: >-
                devops/prometheus/prometheus_troubleshooting.md
      - Linux:
          - brew: linux/brew.md
          - elasticsearch: linux/elasticsearch.md
          - fail2ban: linux/fail2ban.md
          - google chrome: linux/google_chrome.md
          - HAProxy: linux/haproxy.md
          - hypothesis: linux/hypothesis.md
          - LUKS: linux/luks/luks.md
          - mkdocs: linux/mkdocs.md
          - monica: linux/monica.md
          - Miscellaneous Linux Commands: linux/linux_miscellaneous.md
          - nodejs: linux/nodejs.md
          - rm: linux/rm.md
          - Syncthing: linux/syncthing.md
          - Vim:
              - Vim Plugins: linux/vim/vim_plugins.md
          - Wireguard: linux/wireguard.md
          - ZFS: linux/zfs.md
          - zip: linux/zip.md
      - API Management:
          - API Management: devops/api_management.md
          - Kong: devops/kong/kong.md
  - Coding:
      - TDD: coding/tdd.md
      - Python:
          - Python Project Template:
              - Project Template: coding/python/python_project_template.md
              - Command-line Project Template:
                  - Command-line Project Template: >-
                      coding/python/python_project_template/python_cli_template.md
                  - Configure SQLAlchemy for projects without flask: >-
                      coding/python/python_project_template/python_sqlalchemy_without_flask.md
              - Flask Project Template: >-
                  coding/python/python_project_template/python_flask_template.md
              - Microservices Project Template: >-
                  coding/python/python_project_template/python_microservices_template.md
              - Common configurations:
                  - Create the documentation repository: >-
                      coding/python/python_project_template/python_docs.md
                  - Load config from YAML: coding/python/python_config_yaml.md
                  - Configure SQLAlchemy to use the MariaDB/Mysql backend: >-
                      coding/python/python_project_template/python_sqlalchemy_mariadb.md
                  - Configure Docker to host the application: >-
                      coding/python/python_project_template/python_docker.md
          - Libraries:
              - Alembic: coding/python/alembic.md
              - Click: coding/python/click.md
              - Dash: coding/python/dash.md
              - Dash Leaflet: coding/python/dash_leaflet.md
              - DeepDiff: coding/python/deepdiff.md
              - FactoryBoy: coding/python/factoryboy.md
              - Faker: coding/python/faker.md
              - Flask: coding/python/flask.md
              - Folium: coding/python/folium.md
              - Feedparser: coding/python/feedparser.md
              - mkdocstrings: coding/python/mkdocstrings.md
              - Pandas: coding/python/pandas.md
              - Passpy: coding/python/passpy.md
              - Pydantic:
                  - Pydantic: coding/python/pydantic.md
                  - Pydantic Field Types: coding/python/pydantic_types.md
                  - Pydantic Validators: coding/python/pydantic_validators.md
                  - Pydantic Exporting Models: coding/python/pydantic_exporting.md
                  - Pydantic Validating Functions: coding/python/pydantic_functions.md
                  - Pydantic Mypy Plugin: coding/python/pydantic_mypy_plugin.md
              - Pypika: coding/python/pypika.md
              - Plotly: coding/python/plotly.md
              - Ruamel YAML: coding/python/ruamel_yaml.md
              - SQLAlchemy: coding/python/sqlalchemy.md
              - Redis-py: coding/python/redis-py.md
              - Requests-mock: coding/python/requests_mock.md
              - Rq: coding/python/rq.md
              - sh: coding/python/sh.md
              - TinyDB: coding/python/tinydb.md
              - Yoyo: coding/python/yoyo.md
          - Type Hints: coding/python/type_hints.md
          - Code Styling: coding/python/python_code_styling.md
          - Docstrings: coding/python/docstrings.md
          - Anti-Patterns: coding/python/python_anti_patterns.md
          - Data Classes: coding/python/data_classes.md
          - Pytest:
              - Pytest: coding/python/pytest.md
              - Parametrized testing: coding/python/pytest_parametrized_testing.md
              - Pytest-cases: coding/python/pytest_cases.md
          - Python Snippets: coding/python/python_snippets.md
      - Javascript: coding/javascript/javascript.md
      - JSON: coding/json/json.md
      - React: coding/react/react.md
      - SQL: coding/sql/sql.md
      - YAML: coding/yaml/yaml.md
  - Software Architecture:
      - SOLID: architecture/solid.md
      - Domain Driven Design:
          - Domain Driven Design: architecture/domain_driven_design.md
          - Repository Pattern: architecture/repository_pattern.md
          - Service Layer Pattern: architecture/service_layer_pattern.md
      - Database Architecture: architecture/database_architecture.md
      - ORM, Query Builder or Raw SQL: architecture/orm_builder_query_or_raw_sql.md
      - Microservices: architecture/microservices.md
      - Restful APIS: architecture/restful_apis.md
      - Redis: architecture/redis.md
  - Data Analysis:
      - Recommender Systems: >-
          data_analysis/recommender_systems/recommender_systems.md
  - Life Automation:
      - Life Automation: life_automation/life_automation.md
      - Week Automation: life_automation/week_automation.md
      - Relationship Automation: life_automation/relationship_automation.md
      - Vim Automation: life_automation/vim_automation.md
  - Health:
      - Sleep: sleep.md
  - Arts:
    - Writing:
        - Writing: writing/writing.md
        - English Grammar and Ortography: writing/orthography.md
    - Dancing:
      - Rave Dances: dancing/rave_dances.md
      - Shuffle:
        - Basics: dancing/shuffle_basics.md
        - Kicks: dancing/shuffle_kicks.md
        - Spins: dancing/shuffle_spins.md
      - Cutting Shapes: dancing/cutting_shapes_basics.md
    - Meditation: docs/meditation.md
    - Drawing:
        - Drawing: drawing/drawing.md
        - Exercise Pool: drawing/exercise_pool.md
  - Psychology:
      - The XY Problem: psychology/the_xy_problem.md
  - Botany:
      - Trees: botany/trees.md
  - Emojis: emojis.md
  - Contact: contact.md

plugins:
  - search
  - autolinks
  - git-revision-date-localized:
      type: timeago
  - minify:
      minify_html: true

markdown_extensions:
  - abbr
  - admonition
  - meta
  - def_list
  - toc:
      permalink: true
      baselevel: 2
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
theme:
  name: material
  custom_dir: theme
  logo: img/logo.bmp
  features:
    - navigation.instant
  palette:
    scheme: default
    primary: blue grey
    accent: light blue

extra_css:
  - 'stylesheets/extra.css'
  - 'stylesheets/links.css'

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/lyz-code

repo_name: lyz-code/blue-book
repo_url: https://github.com/lyz-code/blue-book
